jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Install Dependencies
        run: npm ci
      - name: Build Site
        run: npm run build
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build

deploy:
  environment:
    name: github-pages
    url: ${{ steps.deployment.outputs.page_url }}
  runs-on: ubuntu-latest
  needs: build
  steps:
    - name: Deploy to Pages
      id: deployment
      uses: actions/deploy-pages@v1
